### ISSUE TITLE
XFX rx580 8GB Hynix H5GC8H24AJ no supported memory found

### ISSUE THREAD

**Issue by TexasTomBF** [IndeedMiners/PolarisBiosEditor#17] opened 2021-03-03 14:00 UTC
I get the "no supported memory found" when I apply one click to stock BIOS. Stock BIOS attached.

**Comment by TexasTomBF** [comment] 2021-03-03 14:03
[first_rig-0-RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-113-58085HAD0-W90.zip](https://github.com/IndeedMiners/PolarisBiosEditor/files/6076455/first_rig-0-RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-113-58085HAD0-W90.zip)

**Comment by oski02** [comment] 2021-03-03 16:41
Hi, I have the same problem.

VRAM: H5GC8H24AJ (HYNIX_4)

**Comment by TexasTomBF** [comment] 2021-03-03 17:08
I decided to try the file despite the error msg, worked like a charm!

**Comment by f0rtem** [comment] 2021-04-05 08:46
> 
> 
> I decided to try the file despite the error msg, worked like a charm!

What you mean it worked? It boosted mh?

**Comment by chruzie** [comment] 2021-04-10 02:19
Thanks @TexasTomBF !

I exported that generated ROM, saved it, and flashed it. Even though you cannot apply from within the program itself, if you export and upload using the ATI tool it'll work. 

Duplicate of #20

**Comment by cryptominingarg** [comment] 2021-04-18 19:49
> Thanks @TexasTomBF !
> 
> I exported that generated ROM, saved it, and flashed it. Even though you cannot apply from within the program itself, if you export and upload using the ATI tool it'll work.
> 
> Duplicate of #20



> Thanks @TexasTomBF !
> 
> I exported that generated ROM, saved it, and flashed it. Even though you cannot apply from within the program itself, if you export and upload using the ATI tool it'll work.
> 
> Duplicate of #20

hi, how do i flash with ATI tool with Hive OS, could you explain that process to me.. i usually upload bios and flash them from HiveOS.

**Comment by umester** [comment] 2021-06-05 22:45
Same Problem here and saving after error msg does NOT change the rom-content here, the files are bit-identic ;-)
Card is 
[RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-113-58085HAD0-M80.zip]

(https://github.com/IndeedMiners/PolarisBiosEditor/files/6603357/RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-113-58085HAD0-M80.zip)

Do I need to change the bios-switch on the card to "game mode" before downloading the bios? Now it's in "mine mode"? 
Are both bios modes downloaded?

**Comment by elstukov** [comment] 2021-08-01 00:24
Did the same, but using the new rom after getting the error results on the GPU not been recognized. No video, nothing. Had to connect it as a secondary gpu to re flash it to stock bios

#28     Link to an issue for the MSI RX 590  H5GC8H24AJ Hynix

**Comment by mister-vio** [comment] 2021-08-23 12:46
same issue here.
Radeon RX 580 8192 MB · XFX
SK Hynix H5GC8H24AJR · 113-580S8HAF1-W90

**Comment by IndeedMiners** [comment] 2021-12-25 11:54
Fixed in PBE [1.7.6](https://github.com/IndeedMiners/PolarisBiosEditor/releases/)

**Closed as completed by IndeedMiners** 2021-12-25 11:54 UTC
